### There are 5 workdays, 10 hours each day, and 15 minute blocks of time, so 200 blocks alltogether.
roster = [
{'id' => 0, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 1, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 2, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 3, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 4, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 5, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 6, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 7, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 8, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 9, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 10, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 11, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 12, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 13, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 14, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 15, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 16, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 17, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 18, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 19, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 20, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 21, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 22, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 23, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 24, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 25, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 26, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 27, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 28, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 29, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 30, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 31, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 32, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 33, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 34, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 35, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 36, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 37, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 38, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 39, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 40, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 41, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 42, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 43, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 44, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 45, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 46, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 47, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 48, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 49, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 50, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 51, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 52, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 53, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 54, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 55, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 56, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 57, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 58, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 59, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 60, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 61, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 62, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 63, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 64, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 65, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 66, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 67, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 68, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 69, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 70, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 71, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 72, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 73, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 74, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 75, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 76, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 77, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 78, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 79, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 80, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 81, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 82, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 83, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 84, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 85, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 86, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 87, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 88, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 89, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 90, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 91, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 92, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 93, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 94, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 95, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 96, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 97, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 98, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 99, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 100, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 101, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 102, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 103, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 104, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 105, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 106, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 107, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 108, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 109, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 110, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 111, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 112, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 113, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 114, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 115, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 116, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 117, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 118, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 119, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 120, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 121, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 122, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 123, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 124, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 125, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 126, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 127, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 128, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 129, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 130, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 131, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 132, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 133, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 134, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 135, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 136, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 137, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 138, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 139, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 140, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 141, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 142, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 143, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 144, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 145, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 146, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 147, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 148, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 149, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 150, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 151, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 152, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 153, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 154, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 155, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 156, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 157, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 158, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 159, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 160, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 161, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 162, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 163, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 164, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 165, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 166, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 167, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 168, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 169, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 170, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 171, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 172, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 173, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 174, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 175, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 176, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 177, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 178, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 179, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 180, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 181, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 182, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 183, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 184, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 185, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 186, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 187, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 188, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 189, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 190, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 191, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 192, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 193, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 194, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 195, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 196, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 197, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 198, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},
{'id' => 199, 'staff_needed'=>5,'overstaffed'=>-5,'active_requests'=>[],'inactive_requests'=>[]},

]

### There are 20 employees, each with a max time of 20 hours a week (or 80 15 minute blocks), 
### and a min time of 10 hours (or 40 blocks). 

employees = [
{"id"=>0,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},{"id"=>1,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>2,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>3,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>4,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>5,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>6,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>7,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>8,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>9,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>10,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>11,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>12,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>13,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>14,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>15,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>16,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>17,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>18,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},
{"id"=>19,"max"=>80,"min"=>40,"num_scheduled_blocks"=>0,"blocks_over" = 0,"blocks_under" = 40},

]

### Generate requests randomly... each employee requests an amount of time that is between twice the minimum and twice the maximum amount of requested time.

requests = []

i=0
employees.each{|employee| 
	
}
